# Generated by Django 3.1.4 on 2021-12-23 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='started_class',
            name='students_completed',
            field=models.ManyToManyField(blank=True, related_name='students_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='started_class',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='students_enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
