# Generated by Django 3.1.4 on 2021-12-24 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0002_auto_20211223_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=70)),
                ('num_assign', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='num_assignments',
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='students_completed',
        ),
        migrations.AddField(
            model_name='started_class',
            name='students_completed',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='students_enrolled',
        ),
        migrations.AddField(
            model_name='started_class',
            name='students_enrolled',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='started_class',
            name='course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_started', to='Learn_Now.course'),
        ),
    ]
