# Generated by Django 3.1.4 on 2021-12-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0003_auto_20211224_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_assign',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
