# Generated by Django 3.1.4 on 2021-12-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0004_auto_20211224_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='started_class',
            name='students_completed',
        ),
    ]
