# Generated by Django 3.1.4 on 2021-12-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0005_remove_started_class_students_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='started_class',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
