# Generated by Django 3.1.4 on 2021-12-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0006_started_class_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
