# Generated by Django 3.1.4 on 2021-12-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0007_course_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='future',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
