# Generated by Django 3.1.4 on 2021-12-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0008_auto_20211226_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_num', models.IntegerField(default=0)),
                ('question_1', models.CharField(max_length=300)),
                ('quest1_ans', models.BooleanField()),
                ('question_2', models.CharField(max_length=300)),
                ('quest2_ans', models.BooleanField()),
                ('question_3', models.CharField(max_length=300)),
                ('quest3_ans', models.BooleanField()),
                ('question_4', models.CharField(max_length=300)),
                ('quest4_ans', models.BooleanField()),
                ('question_5', models.CharField(max_length=300)),
                ('quest5_ans', models.BooleanField()),
                ('question_6', models.CharField(max_length=300)),
                ('quest6_ans', models.BooleanField()),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Learn_Now.course')),
            ],
        ),
    ]
