# Generated by Django 3.1.4 on 2021-12-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0009_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quest6_ans',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_6',
        ),
    ]
