# Generated by Django 3.1.4 on 2021-12-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0010_auto_20211228_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_info',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
