# Generated by Django 3.1.4 on 2022-01-08 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0012_course_current_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_completed',
            field=models.ManyToManyField(blank=True, related_name='students_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_students',
            field=models.ManyToManyField(blank=True, related_name='current_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
