# Generated by Django 3.1.4 on 2022-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0014_quiz_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='started_class',
            name='assign_1_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='started_class',
            name='assign_2_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='started_class',
            name='assign_3_complete',
            field=models.BooleanField(default=False),
        ),
    ]
