# Generated by Django 3.1.4 on 2022-01-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0016_course_lectures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_lectures',
            old_name='lecture',
            new_name='lecture_num',
        ),
        migrations.RenameField(
            model_name='course_lectures',
            old_name='intro_vid',
            new_name='lecture_vid',
        ),
        migrations.AddField(
            model_name='course',
            name='intro_vid',
            field=models.URLField(blank=True, max_length=220),
        ),
    ]
