# Generated by Django 3.1.4 on 2022-01-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0017_auto_20220119_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_lectures',
            name='lecture_info',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
