# Generated by Django 3.1.4 on 2022-01-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0018_course_lectures_lecture_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_lectures',
            name='lecture_title',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
