# Generated by Django 3.1.4 on 2022-01-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0019_course_lectures_lecture_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='started_class',
            name='assign_1',
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='assign_1_complete',
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='assign_2',
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='assign_2_complete',
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='assign_3',
        ),
        migrations.RemoveField(
            model_name='started_class',
            name='assign_3_complete',
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_num', models.IntegerField(blank=True)),
                ('assign_score', models.IntegerField(blank=True)),
                ('assign_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_course', to='Learn_Now.course')),
            ],
        ),
    ]
