# Generated by Django 3.1.4 on 2022-01-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0020_auto_20220119_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assign_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='assign_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
