# Generated by Django 3.1.4 on 2022-01-19 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0022_assignments_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_discription', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_unit', to='Learn_Now.course_unit'),
        ),
    ]
