# Generated by Django 3.1.4 on 2022-01-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn_Now', '0023_auto_20220119_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_lectures',
            name='lecture_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
